version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&sudo apt-get install -y nodejs
  pre_build:
    commands:
      - echo installing dependencies...
      - cd webapp
      - npm install
      - npm run build
  build:
    commands:
      # - echo testing...
      # - echo building...
      - npm install
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/
